env_name: 'multiUAV'
n_steps: 1024
mini_batch_size: 256
max_train_steps: 1000000
lr_a: 0.0001
lr_c: 0.001
gamma: 0.99
lamda: 0.98
epsilon: 0.1
K_epochs: 4
entropy_coef: 0.02
num_envs: 24
normalize_state: False
normalize_reward: False
is_continuous: False
clip_decay: False
lr_decay: False
seed: 42
critic_hidden: [128, 128]
actor_hidden: [64, 64]
use_quantum: false
